package com.dbt.webservice.siebel;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * TB_spcSync_spcEnd_spcFor_spcCMS_spcService service = new TB_spcSync_spcEnd_spcFor_spcCMS_spcService();
 * TBSpcSyncSpcEndSpcForSpcCMSSpcService portType = service.getTBSpcSyncSpcEndSpcForSpcCMSSpcService();
 * portType.newRouteForCMS(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "TB_spcSync_spcEnd_spcFor_spcCMS_spcService", targetNamespace = "http://siebel.com/CustomUI", wsdlLocation = "file:/C:/Users/john/Desktop/New%20TB%20Sync%20End%20For%20CMS%20Service.WSDL")
public class TBSpcSyncSpcEndSpcForSpcCMSSpcService_Service extends Service {

	public static void main(String []args){
	//	String address= cn.com.benyoyo.manage.bs.env.webservice.siebel.TBSpcSyncSpcEndSpcForSpcCMSSpcService_Service.class.getResource(".").getFile();
		String spec =TBSpcSyncSpcEndSpcForSpcCMSSpcService_Service.class.getResource(".").getFile()+"New TB Sync End For CMS Service.WSDL";
	   log.warn(spec);
	}
	private final static URL TBSPCSYNCSPCENDSPCFORSPCCMSSPCSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.dbt.webservice.siebel.TBSpcSyncSpcEndSpcForSpcCMSSpcService_Service.class
					.getName());
	private final static Log log=LogFactory.getLog(TBSpcSyncSpcEndSpcForSpcCMSSpcService_Service.class);

	static {
		URL url = null;
		try {			
			String file = TBSpcSyncSpcEndSpcForSpcCMSSpcService_Service.class.getResource("").getFile();
			String spec ="file:"+file+"New TB Sync End For CMS Service.WSDL"; 
			log.warn(spec);
			URL baseUrl = new URL(spec);		
			url=baseUrl;
			
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/john/Desktop/New%20TB%20Sync%20End%20For%20CMS%20Service.WSDL', retrying as a local file");
			logger.warning(e.getMessage());
		}
		TBSPCSYNCSPCENDSPCFORSPCCMSSPCSERVICE_WSDL_LOCATION = url;
	}

	public TBSpcSyncSpcEndSpcForSpcCMSSpcService_Service(URL wsdlLocation,
			QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public TBSpcSyncSpcEndSpcForSpcCMSSpcService_Service() {
		super(TBSPCSYNCSPCENDSPCFORSPCCMSSPCSERVICE_WSDL_LOCATION, new QName(
				"http://siebel.com/CustomUI",
				"TB_spcSync_spcEnd_spcFor_spcCMS_spcService"));
	}

	/**
	 * 
	 * @return returns TBSpcSyncSpcEndSpcForSpcCMSSpcService
	 */
	@WebEndpoint(name = "TB_spcSync_spcEnd_spcFor_spcCMS_spcService")
	public TBSpcSyncSpcEndSpcForSpcCMSSpcService getTBSpcSyncSpcEndSpcForSpcCMSSpcService() {
		return super.getPort(new QName("http://siebel.com/CustomUI",
				"TB_spcSync_spcEnd_spcFor_spcCMS_spcService"),
				TBSpcSyncSpcEndSpcForSpcCMSSpcService.class);
	}

}
