package com.dbt.webservice.siebel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "TB_spcSync_spcEnd_spcFor_spcCMS_spcService", targetNamespace = "http://siebel.com/CustomUI")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TBSpcSyncSpcEndSpcForSpcCMSSpcService {

	/**
	 * 
	 * @param newRouteForCMSInput
	 * @return returns
	 *         cn.com.benyoyo.manage.bs.env.webservice.siebel.NewRouteForCMSOutput
	 */
	@WebMethod(operationName = "NewRouteForCMS", action = "document/http://siebel.com/CustomUI:NewRouteForCMS")
	@WebResult(name = "NewRouteForCMS_Output", targetNamespace = "http://siebel.com/CustomUI", partName = "NewRouteForCMS_Output")
	public NewRouteForCMSOutput newRouteForCMS(
			@WebParam(name = "NewRouteForCMS_Input", targetNamespace = "http://siebel.com/CustomUI", partName = "NewRouteForCMS_Input") NewRouteForCMSInput newRouteForCMSInput);

	/**
	 * 
	 * @param newEndForCMSInput
	 * @return returns
	 *         cn.com.benyoyo.manage.bs.env.webservice.siebel.NewEndForCMSOutput
	 */
	@WebMethod(operationName = "NewEndForCMS", action = "document/http://siebel.com/CustomUI:NewEndForCMS")
	@WebResult(name = "NewEndForCMS_Output", targetNamespace = "http://siebel.com/CustomUI", partName = "NewEndForCMS_Output")
	public NewEndForCMSOutput newEndForCMS(
			@WebParam(name = "NewEndForCMS_Input", targetNamespace = "http://siebel.com/CustomUI", partName = "NewEndForCMS_Input") NewEndForCMSInput newEndForCMSInput);

	/**
	 * 
	 * @param newGridForCMSInput
	 * @return returns
	 *         cn.com.benyoyo.manage.bs.env.webservice.siebel.NewGridForCMSOutput
	 */
	@WebMethod(operationName = "NewGridForCMS", action = "document/http://siebel.com/CustomUI:NewGridForCMS")
	@WebResult(name = "NewGridForCMS_Output", targetNamespace = "http://siebel.com/CustomUI", partName = "NewGridForCMS_Output")
	public NewGridForCMSOutput newGridForCMS(
			@WebParam(name = "NewGridForCMS_Input", targetNamespace = "http://siebel.com/CustomUI", partName = "NewGridForCMS_Input") NewGridForCMSInput newGridForCMSInput);

}
